<?php

declare(strict_types=1);

namespace Keboola\ComponentBulkModify\Tests\Command;

use Keboola\ComponentBulkModify\Command\SetBranchFeaturesHelper;
use PHPUnit\Framework\TestCase;

class SetBranchFeaturesHelperTest extends TestCase
{
    /**
     * @param array $appData
     * @param array $expectedPatchData
     * @dataProvider appDataProvider
     */
    public function testGetPatchData(array $appData, array $expectedPatchData): void
    {
        $patchData = SetBranchFeaturesHelper::getPatchData($appData);
        self::assertEquals($expectedPatchData, $patchData);
    }

    public function appDataProvider(): array
    {
        return [
            'extractor' => [
                [
                    'id' => 'keboola-test.app-acme-anvil-service',
                    'vendor' => [
                        'id' => 'keboola-test',
                        'name' => 'Keboola Test',
                        'address' => '',
                        'email' => 'devel@keboola.com',
                        'type' => 'other',
                    ],
                    'version' => 177,
                    'name' => 'Acme Anvil Service',
                    'type' => 'extractor',
                    'shortDescription' => 'random-description5c5c2dad6d2b5',
                    'longDescription' => 'Description',
                    'sourceCodeUrl' => null,
                    'requiredMemory' => null,
                    'processTimeout' => null,
                    'features' => ['container-root-user'],
                    'encryption' => false,
                    'network' => 'bridge',
                    'defaultBucket' => false,
                    'defaultBucketStage' => null,
                    'forwardToken' => false,
                    'forwardTokenDetails' => false,
                    'injectEnvironment' => false,
                    'uiOptions' => ['genericDockerUI', 'genericDockerUI-tableInput',],
                    'imageParameters' => [
                        'a' => 'b',
                        'eolMessage' => 'The 24h Acme Anvil Service has been terminated.',
                    ],
                    'stackParameters' => [
                        'connection.keboola.com' => ['c' => 'd'],
                        'connection.eu-central-1.keboola.com' => ['e' => 'f'],
                    ],
                    'testConfiguration' => null,
                    'configurationSchema' => [],
                    'configurationRowSchema' => null,
                    'configurationDescription' => null,
                    'configurationFormat' => 'json',
                    'actions' => [],
                    'logger' => 'standard',
                    'stagingStorageInput' => 'local',
                    'stagingStorageOutput' => 'local',
                    'permissions' => [],
                    'createdOn' => '2018-02-25T20:29:09.000Z',
                    'createdBy' => 'ondrej.popelka@keboola.com',
                    'isPublic' => false,
                    'isPublished' => false,
                    'updatedOn' => '2021-03-05T16:44:54.000Z',
                    'updatedBy' => 'ondrej.popelka@keboola.com',
                    'publishedVersion' => null,
                    'uri' => 'docker/keboola-test.app-acme-anvil-service',
                    'repository' =>  [
                        'type' => 'ecr',
                        'uri' => '147946154733.dkr.ecr.us-east-1...',
                        'tag' => '1.0.8',
                        'options' => [],
                        'digest' => 'sha256:d596741fff3aaa6e8d84339ab919ea4a8422863dc6f3c9f7fd0ba52d7ac56738',
                    ],
                    'publishingStatus' => 'private',
                    'icon' => [
                        32 => null,
                        64 => null,
                        128 => null,
                    ],
                ],
                [],
            ],
            'writer' => [
                [
                    'id' => 'keboola-test.app-acme-anvil-service',
                    'vendor' => [
                        'id' => 'keboola-test',
                        'name' => 'Keboola Test',
                        'address' => '',
                        'email' => 'devel@keboola.com',
                        'type' => 'other',
                    ],
                    'version' => 177,
                    'name' => 'Acme Anvil Service',
                    'type' => 'writer',
                    'shortDescription' => 'random-description5c5c2dad6d2b5',
                    'longDescription' => 'Description',
                    'sourceCodeUrl' => null,
                    'requiredMemory' => null,
                    'processTimeout' => null,
                    'features' => ['container-root-user'],
                    'encryption' => false,
                    'network' => 'bridge',
                    'defaultBucket' => false,
                    'defaultBucketStage' => null,
                    'forwardToken' => false,
                    'forwardTokenDetails' => false,
                    'injectEnvironment' => false,
                    'uiOptions' => ['genericDockerUI', 'genericDockerUI-tableInput',],
                    'imageParameters' => [
                        'a' => 'b',
                        'eolMessage' => 'The 24h Acme Anvil Service has been terminated.',
                    ],
                    'stackParameters' => [
                        'connection.keboola.com' => ['c' => 'd'],
                        'connection.eu-central-1.keboola.com' => ['e' => 'f'],
                    ],
                    'testConfiguration' => null,
                    'configurationSchema' => [],
                    'configurationRowSchema' => null,
                    'configurationDescription' => null,
                    'configurationFormat' => 'json',
                    'actions' => [],
                    'logger' => 'standard',
                    'stagingStorageInput' => 'local',
                    'stagingStorageOutput' => 'local',
                    'permissions' => [],
                    'createdOn' => '2018-02-25T20:29:09.000Z',
                    'createdBy' => 'ondrej.popelka@keboola.com',
                    'isPublic' => false,
                    'isPublished' => false,
                    'updatedOn' => '2021-03-05T16:44:54.000Z',
                    'updatedBy' => 'ondrej.popelka@keboola.com',
                    'publishedVersion' => null,
                    'uri' => 'docker/keboola-test.app-acme-anvil-service',
                    'repository' =>  [
                        'type' => 'ecr',
                        'uri' => '147946154733.dkr.ecr.us-east-1...',
                        'tag' => '1.0.8',
                        'options' => [],
                        'digest' => 'sha256:d596741fff3aaa6e8d84339ab919ea4a8422863dc6f3c9f7fd0ba52d7ac56738',
                    ],
                    'publishingStatus' => 'private',
                    'icon' => [
                        32 => null,
                        64 => null,
                        128 => null,
                    ],
                ],
                [
                    'features' => [
                        'container-root-user',
                        'dev-branch-configuration-unsafe',
                    ],
                ],
            ],
            'application' => [
                [
                    'id' => 'keboola-test.app-acme-anvil-service',
                    'vendor' => [
                        'id' => 'keboola-test',
                        'name' => 'Keboola Test',
                        'address' => '',
                        'email' => 'devel@keboola.com',
                        'type' => 'other',
                    ],
                    'version' => 177,
                    'name' => 'Acme Anvil Service',
                    'type' => 'application',
                    'shortDescription' => 'random-description5c5c2dad6d2b5',
                    'longDescription' => 'Description',
                    'sourceCodeUrl' => null,
                    'requiredMemory' => null,
                    'processTimeout' => null,
                    'features' => ['container-root-user'],
                    'encryption' => false,
                    'network' => 'bridge',
                    'defaultBucket' => false,
                    'defaultBucketStage' => null,
                    'forwardToken' => false,
                    'forwardTokenDetails' => false,
                    'injectEnvironment' => false,
                    'uiOptions' => ['genericDockerUI', 'genericDockerUI-tableInput',],
                    'imageParameters' => [
                        'a' => 'b',
                        'eolMessage' => 'The 24h Acme Anvil Service has been terminated.',
                    ],
                    'stackParameters' => [
                        'connection.keboola.com' => ['c' => 'd'],
                        'connection.eu-central-1.keboola.com' => ['e' => 'f'],
                    ],
                    'testConfiguration' => null,
                    'configurationSchema' => [],
                    'configurationRowSchema' => null,
                    'configurationDescription' => null,
                    'configurationFormat' => 'json',
                    'actions' => [],
                    'logger' => 'standard',
                    'stagingStorageInput' => 'local',
                    'stagingStorageOutput' => 'local',
                    'permissions' => [],
                    'createdOn' => '2018-02-25T20:29:09.000Z',
                    'createdBy' => 'ondrej.popelka@keboola.com',
                    'isPublic' => false,
                    'isPublished' => false,
                    'updatedOn' => '2021-03-05T16:44:54.000Z',
                    'updatedBy' => 'ondrej.popelka@keboola.com',
                    'publishedVersion' => null,
                    'uri' => 'docker/keboola-test.app-acme-anvil-service',
                    'repository' =>  [
                        'type' => 'ecr',
                        'uri' => '147946154733.dkr.ecr.us-east-1...',
                        'tag' => '1.0.8',
                        'options' => [],
                        'digest' => 'sha256:d596741fff3aaa6e8d84339ab919ea4a8422863dc6f3c9f7fd0ba52d7ac56738',
                    ],
                    'publishingStatus' => 'private',
                    'icon' => [
                        32 => null,
                        64 => null,
                        128 => null,
                    ],
                ],
                [
                    'features' => [
                        'container-root-user',
                        'dev-branch-configuration-unsafe',
                    ],
                ],
            ],
            'extractor_fwd_token' => [
                [
                    'id' => 'keboola-test.app-acme-anvil-service',
                    'vendor' => [
                        'id' => 'keboola-test',
                        'name' => 'Keboola Test',
                        'address' => '',
                        'email' => 'devel@keboola.com',
                        'type' => 'other',
                    ],
                    'version' => 177,
                    'name' => 'Acme Anvil Service',
                    'type' => 'extractor',
                    'shortDescription' => 'random-description5c5c2dad6d2b5',
                    'longDescription' => 'Description',
                    'sourceCodeUrl' => null,
                    'requiredMemory' => null,
                    'processTimeout' => null,
                    'features' => ['container-root-user'],
                    'encryption' => false,
                    'network' => 'bridge',
                    'defaultBucket' => false,
                    'defaultBucketStage' => null,
                    'forwardToken' => true,
                    'forwardTokenDetails' => false,
                    'injectEnvironment' => false,
                    'uiOptions' => ['genericDockerUI', 'genericDockerUI-tableInput',],
                    'imageParameters' => [
                        'a' => 'b',
                        'eolMessage' => 'The 24h Acme Anvil Service has been terminated.',
                    ],
                    'stackParameters' => [
                        'connection.keboola.com' => ['c' => 'd'],
                        'connection.eu-central-1.keboola.com' => ['e' => 'f'],
                    ],
                    'testConfiguration' => null,
                    'configurationSchema' => [],
                    'configurationRowSchema' => null,
                    'configurationDescription' => null,
                    'configurationFormat' => 'json',
                    'actions' => [],
                    'logger' => 'standard',
                    'stagingStorageInput' => 'local',
                    'stagingStorageOutput' => 'local',
                    'permissions' => [],
                    'createdOn' => '2018-02-25T20:29:09.000Z',
                    'createdBy' => 'ondrej.popelka@keboola.com',
                    'isPublic' => false,
                    'isPublished' => false,
                    'updatedOn' => '2021-03-05T16:44:54.000Z',
                    'updatedBy' => 'ondrej.popelka@keboola.com',
                    'publishedVersion' => null,
                    'uri' => 'docker/keboola-test.app-acme-anvil-service',
                    'repository' =>  [
                        'type' => 'ecr',
                        'uri' => '147946154733.dkr.ecr.us-east-1....',
                        'tag' => '1.0.8',
                        'options' => [],
                        'digest' => 'sha256:d596741fff3aaa6e8d84339ab919ea4a8422863dc6f3c9f7fd0ba52d7ac56738',
                    ],
                    'publishingStatus' => 'private',
                    'icon' => [
                        32 => null,
                        64 => null,
                        128 => null,
                    ],
                ],
                [
                    'features' => [
                        'container-root-user',
                        'dev-branch-job-blocked',
                    ],
                ],
            ],
            'writer_fwd_token' => [
                [
                    'id' => 'keboola-test.app-acme-anvil-service',
                    'vendor' => [
                        'id' => 'keboola-test',
                        'name' => 'Keboola Test',
                        'address' => '',
                        'email' => 'devel@keboola.com',
                        'type' => 'other',
                    ],
                    'version' => 177,
                    'name' => 'Acme Anvil Service',
                    'type' => 'writer',
                    'shortDescription' => 'random-description5c5c2dad6d2b5',
                    'longDescription' => 'Description',
                    'sourceCodeUrl' => null,
                    'requiredMemory' => null,
                    'processTimeout' => null,
                    'features' => ['container-root-user'],
                    'encryption' => false,
                    'network' => 'bridge',
                    'defaultBucket' => false,
                    'defaultBucketStage' => null,
                    'forwardToken' => true,
                    'forwardTokenDetails' => false,
                    'injectEnvironment' => false,
                    'uiOptions' => ['genericDockerUI', 'genericDockerUI-tableInput',],
                    'imageParameters' => [
                        'a' => 'b',
                        'eolMessage' => 'The 24h Acme Anvil Service has been terminated.',
                    ],
                    'stackParameters' => [
                        'connection.keboola.com' => ['c' => 'd'],
                        'connection.eu-central-1.keboola.com' => ['e' => 'f'],
                    ],
                    'testConfiguration' => null,
                    'configurationSchema' => [],
                    'configurationRowSchema' => null,
                    'configurationDescription' => null,
                    'configurationFormat' => 'json',
                    'actions' => [],
                    'logger' => 'standard',
                    'stagingStorageInput' => 'local',
                    'stagingStorageOutput' => 'local',
                    'permissions' => [],
                    'createdOn' => '2018-02-25T20:29:09.000Z',
                    'createdBy' => 'ondrej.popelka@keboola.com',
                    'isPublic' => false,
                    'isPublished' => false,
                    'updatedOn' => '2021-03-05T16:44:54.000Z',
                    'updatedBy' => 'ondrej.popelka@keboola.com',
                    'publishedVersion' => null,
                    'uri' => 'docker/keboola-test.app-acme-anvil-service',
                    'repository' =>  [
                        'type' => 'ecr',
                        'uri' => '147946154733.dkr.ecr.us-east-1...',
                        'tag' => '1.0.8',
                        'options' => [],
                        'digest' => 'sha256:d596741fff3aaa6e8d84339ab919ea4a8422863dc6f3c9f7fd0ba52d7ac56738',
                    ],
                    'publishingStatus' => 'private',
                    'icon' => [
                        32 => null,
                        64 => null,
                        128 => null,
                    ],
                ],
                [
                    'features' => [
                        'container-root-user',
                        'dev-branch-configuration-unsafe',
                        'dev-branch-job-blocked',
                    ],
                ],
            ],
            'already_set' => [
                [
                    'id' => 'keboola-test.app-acme-anvil-service',
                    'vendor' => [
                        'id' => 'keboola-test',
                        'name' => 'Keboola Test',
                        'address' => '',
                        'email' => 'devel@keboola.com',
                        'type' => 'other',
                    ],
                    'version' => 177,
                    'name' => 'Acme Anvil Service',
                    'type' => 'application',
                    'shortDescription' => 'random-description5c5c2dad6d2b5',
                    'longDescription' => 'Description',
                    'sourceCodeUrl' => null,
                    'requiredMemory' => null,
                    'processTimeout' => null,
                    'features' => [
                        'container-root-user',
                        'dev-branch-configuration-unsafe',
                        'dev-branch-job-blocked',
                    ],
                    'encryption' => false,
                    'network' => 'bridge',
                    'defaultBucket' => false,
                    'defaultBucketStage' => null,
                    'forwardToken' => true,
                    'forwardTokenDetails' => false,
                    'injectEnvironment' => false,
                    'uiOptions' => ['genericDockerUI', 'genericDockerUI-tableInput',],
                    'imageParameters' => [
                        'a' => 'b',
                        'eolMessage' => 'The 24h Acme Anvil Service has been terminated.',
                    ],
                    'stackParameters' => [
                        'connection.keboola.com' => ['c' => 'd'],
                        'connection.eu-central-1.keboola.com' => ['e' => 'f'],
                    ],
                    'testConfiguration' => null,
                    'configurationSchema' => [],
                    'configurationRowSchema' => null,
                    'configurationDescription' => null,
                    'configurationFormat' => 'json',
                    'actions' => [],
                    'logger' => 'standard',
                    'stagingStorageInput' => 'local',
                    'stagingStorageOutput' => 'local',
                    'permissions' => [],
                    'createdOn' => '2018-02-25T20:29:09.000Z',
                    'createdBy' => 'ondrej.popelka@keboola.com',
                    'isPublic' => false,
                    'isPublished' => false,
                    'updatedOn' => '2021-03-05T16:44:54.000Z',
                    'updatedBy' => 'ondrej.popelka@keboola.com',
                    'publishedVersion' => null,
                    'uri' => 'docker/keboola-test.app-acme-anvil-service',
                    'repository' =>  [
                        'type' => 'ecr',
                        'uri' => '147946154733.dkr.ecr.us-east-1....',
                        'tag' => '1.0.8',
                        'options' => [],
                        'digest' => 'sha256:d596741fff3aaa6e8d84339ab919ea4a8422863dc6f3c9f7fd0ba52d7ac56738',
                    ],
                    'publishingStatus' => 'private',
                    'icon' => [
                        32 => null,
                        64 => null,
                        128 => null,
                    ],
                ],
                [
                    'features' => [
                        'container-root-user',
                        'dev-branch-configuration-unsafe',
                        'dev-branch-job-blocked',
                    ],
                ],
            ],
        ];
    }
}
